### ISSUE TITLE
git problem

### ISSUE THREAD

**Issue by gefin** [george-hopkins/opentom#11]
my git version 1.7.10.4, updated debian 7 don`t understand the -C in
git -C microwin checkout ....
Can we use a more compatible syntax?

Gernot

**Comment by MatrixMike** [comment]
Hi Gernot,

looks like your git is even older than mine was a few months ago...   I 
added a help-self remember note to my 'tips' file -- see

https://github.com/MatrixMike/Linux-tricks-and-tips/blob/master/tips1.txt

regards, Mike

**Comment by gefin** [comment]
Thanks, i think there is a  simple solution..
[ -f $1 ] || { cd ../build && git clone git://microwindows.org/microwin && cd microwin && git checkout 9ffcd17 && cd .. &&tar czf ../Downloads/microwin_9ffcd17.tgz microwin; }

**Comment by george-hopkins** [comment]
Thanks for your report Gernot! I just pushed the fix to `master`. Would you mind testing again?

**Comment by gefin** [comment]
I tried your master. Git work now well.
