### ISSUE TITLE
User "root" is broken

### ISSUE THREAD

**Issue by gefin** [george-hopkins/opentom#13]
the new build process work great, but telnet and ssh login don't work.
dropbear can't access the root user: login attempt for nonexistent user from....

I think this comes because the now unused "empty_initramfs.tar.gz " is not real empty. 
It contains some files like /etc/passwd who now missed. 

A quick runtime workaround is adding "echo root::0:0:root:/:/bin/sh >/etc/passwd" to start.sh
_________
tuxchess is broken because the include path is wrong
_________
OpenDUNE is broken. Some patches fail.

**Comment by george-hopkins** [comment]
Thank you for reporting the issue. You're absolutely right: These files were not included. I did extract them and added them to my working tree. However, I totally forget add and commit them.

As for tuxchess: Thanks to your fix, it's working again :+1: 
![tuxchess](https://cloud.githubusercontent.com/assets/552590/20636658/3b29986e-b371-11e6-9d5a-99ce026f88ac.png)

OpenDUNE is working again too, see #14 for details.

**Comment by gefin** [comment]
Thanks,
root and tuxchess work well
