### ISSUE TITLE
Include pppd?

### ISSUE THREAD

**Issue by george-hopkins** [george-hopkins/opentom#15]
As mentioned in #12, `pppd` is currently not included in OpenTom. I think including it is certainly worth considering. Especially based on the fact that it is included in the original distribution.

@gefin I have to admit that I'm not very familiar with PPP. What benefits/features does `pppd` provide over `start_bt_sh_listenner`/`picocom /dev/rfcommX`?

**Comment by gefin** [comment]
ppp create a network device on both sides of connection. If you enable forwarding on the PC you can surf the internet with Dillo, use scp or netcat(enable in busybox).
Also multiple shell connections with telnet or remote command execution with ssh are possible.

**Comment by george-hopkins** [comment]
I see, this is quite useful indeed. Based on your pull-request #16, support for PPP is now included.

Thank you for your contributions!
