### ISSUE TITLE
Build Navit with CMake

### ISSUE THREAD

**Issue by george-hopkins** [george-hopkins/opentom#17]
As Navit is [moving away](http://trac.navit-project.org/ticket/1341) from autotools, the build process for Navit must be updated. Most of the changes landed with navit-gps/navit#119 and haven't been released yet.

There is a branch `navit` for people interested in testing the new build.

**Comment by gefin** [comment]
Great. My cmake build did not work yet.
This build work with some small problems:
_____________
-->>> graphics
Disabled  sdl ( Required library not found )

I added "-DSDLIMAGE_LIB_DIR=$(ARM_SYSROOT)/usr/lib/SDL -DLIBDIR=$(ARM_SYSROOT)/usr/lib -DSDLIMAGE_INCLUDE_DIR=$(ARM_SYSROOT)/usr/include" to the cmake statment. 
Now i get working SDL graphics.
__________________
speak cmdline don't work because librt.so.1 is not found.
librt.so is created in arm-sysroot/usr/lib, but not copied to opentom_dist/lib/librt.so.1

After manual copying speak work (no NLS)
_________________
Some gui icons (the green ticks) in the menu are too big. Some lists show only one line.
I miss the "scaling" settings from the configure script.

**Comment by gefin** [comment]
The icon problem was thät my config use 36px while cmake build use 32px icons. so far no problem...

p.s. ppp and scp work well,

**Comment by george-hopkins** [comment]
Thank you for your feedback!

SDL detection: I couldn't reproduce this issue yet. Which version of CMake do you use? Do `libSDL.so`, `libSDL_image.so` and `libSDL_ttf.so` exist in `arm-sysroot/usr/lib`?

As for `librt.so.1`: It seems that the dependency chain got a bit longer. I updated the installation procedure to process all dependencies.

As for the locales: I'm not sure yet whether we should install over 50 locales. Maybe we could introduce a new variable and use it to set `LANG` on the device and install the correct files.

As for the icons: Were they of different size before? I think this might be a problem which should be fixed by Navit directly (we use the same build options as they do).

**Comment by gefin** [comment]
I think cmake find sometime local installed packages outside the toolchain..
Is SDL installed on your host system ? On my system its not installed.
I use cmake 2.8.9 
The SDL libfiles are at place. I think the include files are searched in the host system by default.

I'm not sure that the gettext problem is only a path thing. Strace show only access of   
/usr/lib/locale/locale-archive , /usr/share/locale/locale.alias and LC_IDENTIFICATION but serving these files did not help or the used files are wrong.
The .mo files are not accessed 

I used 36px icons on a 480x272 screen. 32px are usable.

**Comment by george-hopkins** [comment]
As for gettext: Just to verify we understand each other correctly: The GUI language in Navit can't be set with `LANG=...` even after you copied the correct `navit.mo` to `$DIST`?

If yes, can you check whether you get the same output for the following command?
```bash
$ LANG=sv_SE.utf8 NAVIT_SHAREDIR=$DIST/share/navit strace navit -c $DIST/share/navit/navit.xml 2>&1 | grep ^open | grep navit.mo
open("/mnt/sdcard/opentom/share/locale/sv_SE.utf8/LC_MESSAGES/navit.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/mnt/sdcard/opentom/share/locale/sv_SE/LC_MESSAGES/navit.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/mnt/sdcard/opentom/share/locale/sv.utf8/LC_MESSAGES/navit.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/mnt/sdcard/opentom/share/locale/sv/LC_MESSAGES/navit.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
```

**Comment by gefin** [comment]
i don't get this lines. I think NLS will work if the matching navit.mo is in place.
Actual are only the english mo file is copied to opentom._dist.
On my desktop the GUI is translated with the LANG= setting.
With internal GUI show the "tools" icon the selected locale.

**Comment by gefin** [comment]
Sorry, I get the messages. I try to copy the mo files...
Not at startup, but after accessing the menu.

**Comment by gefin** [comment]
Wow. Thanks, Great.  it translates.
Just the  NAVIT_SHAREDIR setting did not work.

**Comment by gefin** [comment]
Just cloned opentom navit.
The libfreetype fix brake navit:
navit: relocation error: navit: undefined symbol: FTC_ImageCache_LookupScaler
after replacing  libfreetype with the unstripped version navit work again.

I also need -DSDLIMAGE_INCLUDE_DIR=$(ARM_SYSROOT)/usr/include to use sdl graphics.

NLS work with a symbolic link to the correct location.

**Comment by gefin** [comment]
After adding this to navit.sh navit use the correct locale path.
export NAVIT_LOCALEDIR=$DIST/share/locale

The new patch of /navit/CMakeLists.txt generate an error on my system:
CMake Error at navit/CMakeLists.txt:150 (compose_xslt_transform_command):
  Unknown CMake command "compose_xslt_transform_command".

p.s. I added an daemon mode to the power_button command. It can call a user command  on button press or low battery.

**Comment by george-hopkins** [comment]
Thanks for reporting the error. The new patch depends on a XSLT processor like saxon-xslt (`libsaxon-java` on Debian). I updated the README to document the new dependency. Afterwards, `NAVIT_LOCALEDIR` should be set to `/mnt/sdcard/opentom/share/locale` automatically.

**Comment by george-hopkins** [comment]
As for the SDL problem: I will try to reproduce the issue on a clean VM. What operating system do you use to build OpenTom?

**Comment by gefin** [comment]
I use debian 7 32 bit with xfce . It has no SDL in the main system installed.
Linux w 3.2.0-4-686-pae #1 SMP Debian 3.2.82-1 i686 GNU/Linux

I think the Build access sometime includes from the main operating system.

**Comment by gefin** [comment]
I think i have to refresh my build system. Navit built from circleci  need 10-20% less RAM then homebuilt.
Function is in both cases OK. Binary size is near equal.

**Comment by gefin** [comment]
Now i have a working built system:
debian-live-8.6.0-i386-xfce-desktop.iso or debian-live-8.6.0-amd64-xfce-desktop.iso
with 
apt-get install git make gcc cmake saxon.java chrpath autoconf libtool fluid pkg-config g++ libglib2.0-dev imagemagick gawk gettext

The 64 bit version need libc6:i386 to execute the toochain binarys.
Without gawk you get a non working ttsystem.
This setup build the navit trunk and the master trunk except navit-R6816.

**Comment by george-hopkins** [comment]
Great! Thank you for testing!

Because we have now confirmed that OpenTom can be built successfully on at least three systems, I think we just wait for navit-gps/navit#62 to get merged.

Feel free to comment if you find any further issues in the meantime.

**Comment by george-hopkins** [comment]
:tada: All changes got merged and are available in the `master` branch now

**Comment by gefin** [comment]
building master work well.
thanks.

By the way... microwin comes with a minimal launcher application. I use it to start my favor applications.
