### ISSUE TITLE
gltt from TomtomXL need a symlink to work

### ISSUE THREAD

**Issue by gefin** [george-hopkins/opentom#21]
I use this in my rc.gltt: !!! are backticks

 ln -sf /dev/!!!cat /proc/barcelona/gpsdev!!! /dev/gpsdata                                                                                      
 nice --3 gltt -baud ${gl_baudrate} -periodic 1000 -fix_start ${par_fix_start

**Comment by george-hopkins** [comment]
Is this issue resolved with the fix you provided in [#20](https://github.com/george-hopkins/opentom/pull/20/commits/7cdb05c1dab05be6f4377462263bf7228df95a8c)?

**Comment by gefin** [comment]
No, #20 is a fix for SiRFstarIII on TOMTOM 730 without using gltt.

This fix is for devices like TT XL. It use global Hammerhead GPS and need gltt. The gltt extracted from this device need this symlink to find the GPS chip.

**Comment by george-hopkins** [comment]
Oh I see, thank you for clarifying. I pushed a fix in 39e3da0 to get `gltt` working. Does the patch resolve the issue?

**Comment by gefin** [comment]
Thank you. The patch work well. I can suspend and resume running navit. It takes only short time to get the actual position.

I just build the new system. Aside my? local problems It work out of the box. Just install the map.
I'm not sure about the "include SDL" and  "stripped libfreetype" problem in my build environment.
Is the Circleci build (opentom-extra?) OK?
