### ISSUE TITLE
add vehicleprofile for navit

### ISSUE THREAD

**Issue by gefin** [george-hopkins/opentom#22]
After real driving i added a  profile "car-city" to navit_xl.xml. Its equal to car, but has reduced routing depth:
route_depth="4:25%,6:1%,8:6000,18:4000"

The problem was that navit  got and stayed out of sync in munich after a tunnel or after leafing the route.
TT need with the lot of ways and the slow hardware to long to reach the changing car position with the recalculated route.
With the reduced serching depth TT has no problem to get synced to the driving car.
Outside the city the original car setting work well.

**Comment by george-hopkins** [comment]
Thank you for reporting! As the new profile would probably benefit all Navit users, it might be a good idea to report it upstream.

For those interested in adding the new profile to their Navit source tree:
```patch
diff --git a/navit/xslt/tomtom.xslt b/navit/xslt/tomtom.xslt
index 3e34d92..973f2a5 100644
--- a/navit/xslt/tomtom.xslt
+++ b/navit/xslt/tomtom.xslt
@@ -43,6 +43,12 @@
 			<xsl:copy-of select="vehicleprofile[@name='car']"/>
 			<xsl:copy-of select="vehicleprofile[@name='car_shortest']"/>
 			<xsl:copy-of select="vehicleprofile[@name='car_avoid_tolls']"/>
+			<vehicleprofile>
+			    <xsl:copy-of select="vehicleprofile[@name='car']/@*"/>
+			    <xsl:attribute name="name">car_near</xsl:attribute>
+			    <xsl:attribute name="route_depth">4:25%,6:1%,8:6000,18:4000</xsl:attribute>
+			    <xsl:copy-of select="vehicleprofile[@name='car']/node()"/>
+			</vehicleprofile>
 			<xsl:copy-of select="vehicleprofile[@name='bike']"/>
 			<xsl:copy-of select="vehicleprofile[@name='pedestrian']"/>
```

**Comment by gefin** [comment]
yes, this is a good idea.
Thank you.
