### ISSUE TITLE
opentom/opentom_dist/bin/cr3 Error 127 in make extra

### ISSUE THREAD

**Issue by fvclaus** [george-hopkins/opentom#28]
I get the following error when executing `make extra`:

```
Makefile:306: recipe for target '/home/fredo/workspace/opentom/opentom_dist/bin/cr3' failed
make[1]: *** [/home/fredo/workspace/opentom/opentom_dist/bin/cr3] Error 127
make[1]: Leaving directory '/home/fredo/workspace/opentom/applications'
Makefile:80: recipe for target 'extra' failed
make: *** [extra] Error 2
```

Search hits indicate that this is problem with the 32bit/64bit.

**Comment by george-hopkins** [comment]
That might be the problem indeed. Would you mind posting the logs from `applications/logs/cr3.log`?

**Comment by fvclaus** [comment]
`cmake` was missing as a dependency. After installing it, the build succeeded. Thanks for pointing out the log file.
