### ISSUE TITLE
Compiling open Tom 

### ISSUE THREAD

**Issue by davbotjohnson** [george-hopkins/opentom#32]
Could someone send me a copy of an open Tom ad card, so I can put it onto my sd card

Thanks!

**Comment by george-hopkins** [comment]
You can find the latest image on the [front page](https://github.com/george-hopkins/opentom). Just click the button "pre-built image" below the title.

**Comment by davbotjohnson** [comment]
Okay

**Comment by davbotjohnson** [comment]
Thanks, it workes
