### ISSUE TITLE
Missing source for libjpeg

### ISSUE THREAD

**Issue by adiehl** [george-hopkins/opentom#5]
In configs/sources.txt line 7: you refer to ftp://ftp.pl.freebsd.org/vol/rzm1/GraphicsMagick/delegates/libjpeg-6b.tar.gz which is 404 ...
What can I use here instead?

**Comment by gefin** [comment]
the file is moved from rzm1 to rzm4.

**Comment by jtvjan** [comment]
Opened a [pull request](https://github.com/george-hopkins/opentom/pull/7) based on this.

**Comment by george-hopkins** [comment]
Thank you for reporting! As of #7, the link should be fixed.

**Comment by danhans42** [comment]
Broken again
