### ISSUE TITLE
logs dir nonexistent

### ISSUE THREAD

**Issue by adiehl** [george-hopkins/opentom#6]
The dir opentom/logs is not created automatically and make stops here ... mkdir logs would solve this

```
cd kernel && make clean && nice -n 19 make -j6 >/home/adiehl/Downloads/opentom/logs/kernel.log 2>&1
(...)
/bin/sh: 1: cannot create /home/adiehl/Downloads/opentom/logs/kernel.log: Directory nonexistent
```

**Comment by gefin** [comment]
I has also some errors building with debian 7

Work around if glib build failes at garry.so with wrong ELF format:

vi ./build/glib-1.2.10/Makefile ; ... edit the CC line to
  CC = /usr/local/cross/gcc-3.3.4_glibc-2.3.2/bin/arm-linux-gcc
cd ./build/glib-1.2.10
make clean
make
cd ../..
make     ; dont apply the patches again
----------------------------------------------
Workaround for missing lib/ts:
mkdir opentom_dist/lib/ts

**Comment by george-hopkins** [comment]
@adiehl Thank you for reporting!
@gefin Thanks for helping out and providing a PR (see #9) :+1:
